# Generated by Django 3.1.2 on 2020-10-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201003_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avater',
            new_name='avatar',
        ),
    ]
