# Generated by Django 3.1.2 on 2020-10-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201004_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='cehck_out',
            new_name='check_out',
        ),
    ]
